postsubmits:
 xstefank/gcp-test-repo:
  - name: test-postsubmit
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  xstefank/gcp-test-repo:
  - name: test-presubmit
    trigger: "(?m)^/test this"
    rerun_command: "/test this"
    context: test-presubmit
    always_run: true
    skip_report: false
    agent: kubernetes
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]

